function [] = gui()

S.fh = figure('units','pixels',...
              'position',[300 300 200 100],...
              'menubar','none',...
              'name','GUI_9',...
              'numbertitle','off',...
              'resize','off');
S.pb = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 20 160 60],...
                 'string','Push Me',...
                 'callback',{@pb_call},...
                 'backgroundc',[0.94 .94 .94],...
                 'busyaction','cancel',...% So multiple pushes don't stack.
                 'interrupt','off');
global tog;
function [tog] = pb_call(varargin)
tog=1;
